server:
  port: 3344

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qiutdisgood/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7002/eureka
